changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Dependencies
      labels:
        - dependencies
    - title: Security
      labels:
        - security
    - title: Performance
      labels:
        - performance
    - title: Other Changes
      labels:
        - "*"
