#!/usr/bin/env python3
"""
Generates CaBundle.h, a full public root-CA bundle for the ESP32 mbedtls
certificate-bundle verifier (WiFiClientSecure::setCACertBundle). Used by
Updater.h to validate TLS certs for the GitHub API and release asset CDN
without pinning to specific roots — this is a generic public trust store,
not something specific to GitHub.

Binary format matches esp-idf's components/mbedtls/esp_crt_bundle/esp_crt_bundle.c:
  [offset of 1st cert](u32) ... [offset of nth cert](u32)
  [1st cert] ... [nth cert]
  cert = [len(CN)](u16) [len(key)](u16) [CN bytes] [key bytes]
Certs are sorted ascending by CN (DER-encoded subject) for binary search.

Requires: pip install cryptography certifi
Usage: python3 scripts/gen_ca_bundle.py [src/update/CaBundle.h]
"""
import sys
import struct
import certifi
from cryptography import x509
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.serialization import Encoding, PublicFormat

ARRAY_NAME = "CA_BUNDLE"


def load_certs(pem_path):
    with open(pem_path, "rb") as f:
        data = f.read()
    certs = []
    for block in data.split(b"-----BEGIN CERTIFICATE-----"):
        if b"-----END CERTIFICATE-----" not in block:
            continue
        pem = (
            b"-----BEGIN CERTIFICATE-----"
            + block.split(b"-----END CERTIFICATE-----")[0]
            + b"-----END CERTIFICATE-----\n"
        )
        certs.append(x509.load_pem_x509_certificate(pem, default_backend()))
    return certs


def build_bundle(certs):
    entries = []
    for cert in certs:
        cn_der = cert.subject.public_bytes(default_backend())
        key_der = cert.public_key().public_bytes(Encoding.DER, PublicFormat.SubjectPublicKeyInfo)
        if len(cn_der) > 0xFFFF or len(key_der) > 0xFFFF:
            continue
        entries.append((cn_der, key_der))

    entries.sort(key=lambda e: e[0])

    n = len(entries)
    offset_table_size = n * 4
    bodies = []
    offsets = []
    running = offset_table_size
    for cn_der, key_der in entries:
        body = struct.pack("<HH", len(cn_der), len(key_der)) + cn_der + key_der
        offsets.append(running)
        bodies.append(body)
        running += len(body)

    out = b"".join(struct.pack("<I", o) for o in offsets) + b"".join(bodies)
    return out, n


def emit_header(bundle, count, out_path):
    with open(out_path, "w") as f:
        f.write("#pragma once\n")
        f.write("#include <cstdint>\n")
        f.write("#include <cstddef>\n\n")
        f.write(f"// Generated by scripts/gen_ca_bundle.py — {count} root CAs, {len(bundle)} bytes.\n")
        f.write("// Do not edit by hand; re-run the script to refresh the bundle.\n")
        f.write(f"static const uint8_t {ARRAY_NAME}[] = {{\n")
        for i in range(0, len(bundle), 16):
            chunk = bundle[i:i + 16]
            f.write("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n")
        f.write("};\n")
        f.write(f"static const size_t {ARRAY_NAME}_LEN = sizeof({ARRAY_NAME});\n")


if __name__ == "__main__":
    pem_path = certifi.where()
    certs = load_certs(pem_path)
    bundle, count = build_bundle(certs)
    print(f"source PEM: {pem_path}", file=sys.stderr)
    print(f"parsed {len(certs)} certs, {count} usable in bundle", file=sys.stderr)
    print(f"bundle size: {len(bundle)} bytes", file=sys.stderr)
    out_path = sys.argv[1] if len(sys.argv) > 1 else "src/update/CaBundle.h"
    emit_header(bundle, count, out_path)
    print(f"wrote {out_path}", file=sys.stderr)
